blank_issues_enabled: false
contact_links:
  - name: General support
    url: https://github.com/infinitepower18/Homepage-MobileSafari/discussions
    about: For support queries, please post in the project's discussion.