blank_issues_enabled: false
contact_links:
  - name: Known issues
    url: https://github.com/infinitepower18/Homepage-MobileSafari/discussions/17
    about: Before posting, check the known issues to see if your issue is already listed.
  - name: General support
    url: https://github.com/infinitepower18/Homepage-MobileSafari/discussions
    about: For support queries, please post in the project's discussion.
